#!/bin/bash

QEMU=qemu-system-i386
dbg_opt='-S -s'

${QEMU} -fda bootloader.bin ${dbg_opt} &

gdb  \
    -ex 'target remote localhost:1234' \
    -ex 'add-symbol-file bootsect.o 0x7c00' \
    -ex 'add-symbol-file boot2.o 0x7e00' \
    -ex 'break *0x7c00' \
    -ex 'break *0x7e00'
