#!/bin/bash

QEMU=qemu-system-i386
dbg_opt='-S -s'

${QEMU} -fda bootloader.bin ${dbg_opt} &

gdb  \
    -ex 'target remote localhost:1234' \
    -ex 'symbol-file bootloader.o' \
    -ex 'break *0x7c00'
